### ISSUE TITLE
cant handle low fps well

### ISSUE THREAD

**Issue by makc** [pmndrs/racing-game#152]
I have [reported it on twitter ](https://twitter.com/makc3d/status/1404181925577867270)few days ago but I think you missed it, so here goes:
> my guess is you try and fail to handle long frame times? dt = min(dt, 50ms) might fix it

**Comment by Gusted** [comment]
#77 also see: https://github.com/pmndrs/racing-game/issues/77#issuecomment-858736594 and make sure to not have `privacy.resistFingerprinting` enabled they make webGL almost unusable to prevent it from being fingerprinted.

**Comment by makc** [comment]
@Gusted that other ticket is closed with no resolution. Does it mean you just give up on this bug?

**Comment by Gusted** [comment]
> . Does it mean you just give up on this bug?

No... I just said that the current configuration you have and I had was causing this. Like I said make sure not to have any debugging properties enabled on the gpu within `about:config` and disable `privacy.resistFingerprinting` because they fuck up some things that are required.

**Comment by makc** [comment]
even if I do have this setting on (which I dont) it is your project responsibility to degrade gracefully under these circumstances. users should not be poking around in about:config for a random website

**Comment by Gusted** [comment]
> even if I do have this setting on (which I dont)

Try on a new profile, I can tell you that it's most likely a setting causing this.

>  it is your project responsibility to degrade gracefully under these circumstances.

No, no and no. Firefox is on purpose hiding and restricting certain things and a simple workaround won't be possible because that will defeat the purpose of restricting it in the first place. 

>  users should not be poking around in about:config for a random website

Only users who've poked around `about:config` in the first place will experience this. Firefox itself doesn't touch any settings related from the `about:preferences` pages nor does any automatically. 

Back to the point, it shouldn't render with low FPS, there's definitely something going wrong on that end, unless there's something that shows the game is doing something wrong and expensive(get a Firefox Profiler) nothing much to that.

The game should perform just fine under slightly lower FPS when it happens, as the whole browser would be affected by it and thus will run everything a bit slower. However if the GPU can't keep up with what the browser tells to draw... 🤷🏽.

Btw, `dt = min(dt, 50ms) might fix it` what does this mean? We don't have a variable `dt` nor any call to `Math.min()`

**Comment by makc** [comment]
> what does this mean

it is a typical situation when you try to be smart and use a time delta between two game loops instead of fixed step to calculate things like physics or camera animation, but it backfires and huge delta throws your math off.

**Comment by Gusted** [comment]
Could you by any chance open the editor(`.`IIRC) and enable the stats option. It should show you some. Stats in the left top corner. How does it looking and when you click on the little box, it should show you some timing info.

**Comment by makc** [comment]
that only shows me fps counter (says 6). btw! when I exit the editor, the camera is reset (gets far behind the car) and does not roll. the rolling only starts when it gets really close to the car.

**Comment by Gusted** [comment]
Could you get me a https://profiler.firefox.com/ when you are in the game? I'm slightly turning this into a performance problem as, back to topic yes it doesn't handle low fps that well, mainly due to how rAF/react works.

**Comment by makc** [comment]
do you mean this:
[profile.json.zip](https://github.com/pmndrs/racing-game/files/6678884/profile.json.zip)

**Comment by Gusted** [comment]
> do you mean this:
> [profile.json.zip](https://github.com/pmndrs/racing-game/files/6678884/profile.json.zip)

Is that while running the game? Because in that case 96% the time is spend on "idle" which is something more appropriate for the start screen.

**Comment by makc** [comment]
yes, thats during the roll. maybe it does not log what the workers do? I have never profiled workers before

**Comment by Gusted** [comment]
> yes, thats during the roll. maybe it does not log what the workers do? I have never profiled workers before

The new built-in profile can do that. Once again see: https://profiler.firefox.com/ on how to enable that.

**Comment by makc** [comment]
chrome profiler is no better here, wth is `system (self)`... but regardless, the whole point o this issue was that the camera simply should not roll. this is non-issue with high fps, so I take it nobody is gonna look into it - lets just drop it here.

![Screen Shot 2021-06-18 at 22 37 56 ](https://user-images.githubusercontent.com/242577/122609269-66926f80-d086-11eb-8962-367368ecad8a.png)

**Comment by Gusted** [comment]
>  the whole point o this issue was that the camera simply should not roll.

correct, however as outlined it's most likely a underlying issue which was likely the same as #77 which I got. However in this case triggered differently.
